# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tick.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntick.proto\x12\x04tick\"\x07\n\x05\x45mpty\"W\n\x0cRequestPara1\x12\x0c\n\x04\x65xch\x18\x01 \x01(\t\x12\x0b\n\x03ins\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\x12\x13\n\x06period\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\t\n\x07_period\"T\n\x0cRequestPara2\x12\x0c\n\x04\x65xch\x18\x01 \x01(\t\x12\x11\n\x04type\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x64\x61te\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_typeB\x07\n\x05_date\")\n\x0cRequestPara3\x12\x0c\n\x04\x65xch\x18\x01 \x01(\t\x12\x0b\n\x03ins\x18\x02 \x01(\t\"\x19\n\tBytesFlow\x12\x0c\n\x04info\x18\x01 \x01(\x0c\"\x1a\n\nStringFlow\x12\x0c\n\x04info\x18\x01 \x01(\t2\xac\x02\n\x04Tick\x12\x32\n\x07Rawtick\x12\x12.tick.RequestPara1\x1a\x0f.tick.BytesFlow\"\x00\x30\x01\x12\x30\n\x05Kline\x12\x12.tick.RequestPara1\x1a\x0f.tick.BytesFlow\"\x00\x30\x01\x12\x30\n\x05Mline\x12\x12.tick.RequestPara1\x1a\x0f.tick.BytesFlow\"\x00\x30\x01\x12)\n\x04\x45xch\x12\x0b.tick.Empty\x1a\x10.tick.StringFlow\"\x00\x30\x01\x12/\n\x03Ins\x12\x12.tick.RequestPara2\x1a\x10.tick.StringFlow\"\x00\x30\x01\x12\x30\n\x04\x44\x61te\x12\x12.tick.RequestPara3\x1a\x10.tick.StringFlow\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tick_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_REQUESTPARA1']._serialized_start=29
  _globals['_REQUESTPARA1']._serialized_end=116
  _globals['_REQUESTPARA2']._serialized_start=118
  _globals['_REQUESTPARA2']._serialized_end=202
  _globals['_REQUESTPARA3']._serialized_start=204
  _globals['_REQUESTPARA3']._serialized_end=245
  _globals['_BYTESFLOW']._serialized_start=247
  _globals['_BYTESFLOW']._serialized_end=272
  _globals['_STRINGFLOW']._serialized_start=274
  _globals['_STRINGFLOW']._serialized_end=300
  _globals['_TICK']._serialized_start=303
  _globals['_TICK']._serialized_end=603
# @@protoc_insertion_point(module_scope)
