# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tickmine.tick_pb2 as tick__pb2


class TickStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Rawtick = channel.unary_stream(
            '/tick.Tick/Rawtick',
            request_serializer=tick__pb2.RequestPara1.SerializeToString,
            response_deserializer=tick__pb2.BytesFlow.FromString,
        )
        self.Kline = channel.unary_stream(
            '/tick.Tick/Kline',
            request_serializer=tick__pb2.RequestPara1.SerializeToString,
            response_deserializer=tick__pb2.BytesFlow.FromString,
        )
        self.Mline = channel.unary_stream(
            '/tick.Tick/Mline',
            request_serializer=tick__pb2.RequestPara1.SerializeToString,
            response_deserializer=tick__pb2.BytesFlow.FromString,
        )
        self.Exch = channel.unary_stream(
            '/tick.Tick/Exch',
            request_serializer=tick__pb2.Empty.SerializeToString,
            response_deserializer=tick__pb2.StringFlow.FromString,
        )
        self.Ins = channel.unary_stream(
            '/tick.Tick/Ins',
            request_serializer=tick__pb2.RequestPara2.SerializeToString,
            response_deserializer=tick__pb2.StringFlow.FromString,
        )
        self.Date = channel.unary_stream(
            '/tick.Tick/Date',
            request_serializer=tick__pb2.RequestPara3.SerializeToString,
            response_deserializer=tick__pb2.StringFlow.FromString,
        )


class TickServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Rawtick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Kline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Date(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TickServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Rawtick':
        grpc.unary_stream_rpc_method_handler(
            servicer.Rawtick,
            request_deserializer=tick__pb2.RequestPara1.FromString,
            response_serializer=tick__pb2.BytesFlow.SerializeToString,
        ),
        'Kline':
        grpc.unary_stream_rpc_method_handler(
            servicer.Kline,
            request_deserializer=tick__pb2.RequestPara1.FromString,
            response_serializer=tick__pb2.BytesFlow.SerializeToString,
        ),
        'Mline':
        grpc.unary_stream_rpc_method_handler(
            servicer.Mline,
            request_deserializer=tick__pb2.RequestPara1.FromString,
            response_serializer=tick__pb2.BytesFlow.SerializeToString,
        ),
        'Exch':
        grpc.unary_stream_rpc_method_handler(
            servicer.Exch,
            request_deserializer=tick__pb2.Empty.FromString,
            response_serializer=tick__pb2.StringFlow.SerializeToString,
        ),
        'Ins':
        grpc.unary_stream_rpc_method_handler(
            servicer.Ins,
            request_deserializer=tick__pb2.RequestPara2.FromString,
            response_serializer=tick__pb2.StringFlow.SerializeToString,
        ),
        'Date':
        grpc.unary_stream_rpc_method_handler(
            servicer.Date,
            request_deserializer=tick__pb2.RequestPara3.FromString,
            response_serializer=tick__pb2.StringFlow.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler('tick.Tick', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler, ))


# This class is part of an EXPERIMENTAL API.
class Tick(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Rawtick(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Rawtick', tick__pb2.RequestPara1.SerializeToString,
                                              tick__pb2.BytesFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Kline(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Kline', tick__pb2.RequestPara1.SerializeToString,
                                              tick__pb2.BytesFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Mline(request,
              target,
              options=(),
              channel_credentials=None,
              call_credentials=None,
              insecure=False,
              compression=None,
              wait_for_ready=None,
              timeout=None,
              metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Mline', tick__pb2.RequestPara1.SerializeToString,
                                              tick__pb2.BytesFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Exch(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Exch', tick__pb2.Empty.SerializeToString,
                                              tick__pb2.StringFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Ins', tick__pb2.RequestPara2.SerializeToString,
                                              tick__pb2.StringFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Date(request,
             target,
             options=(),
             channel_credentials=None,
             call_credentials=None,
             insecure=False,
             compression=None,
             wait_for_ready=None,
             timeout=None,
             metadata=None):
        return grpc.experimental.unary_stream(request, target, '/tick.Tick/Date', tick__pb2.RequestPara3.SerializeToString,
                                              tick__pb2.StringFlow.FromString, options, channel_credentials, insecure, call_credentials,
                                              compression, wait_for_ready, timeout, metadata)
